### ISSUE TITLE
Library to allow developing alternate UI

### ISSUE THREAD

**Issue by emosenkis** [bbodi/notecalc3#16] opened 2020-12-22 07:01 UTC
It would be really neat if this could expose a library to allow the functionality to be surfaced in another UI - I'm imagining a terminal version, a Vim plugin, etc.

**Comment by bbodi** [comment] 2020-12-22 07:09
Hi,  

I close this issue as it is a duplicate of https://github.com/bbodi/notecalc3/issues/6

And I suggest to read this [comment](https://github.com/bbodi/notecalc3/issues/6#issuecomment-740427484). It describes  that what you suggest is absolutely possible and quite easy. For an example for how to do it, check notecalc.html and the frontend-web rust project, that's it that should be ported for an other platform.

The terminal UI is on my list but with a low priority.

**Closed as completed by bbodi** 2020-12-22 07:09 UTC
